(define (read-lines filename)
  (define (inner port)
    (let ((val (read port)))
      (if (eof-object? val)
        '()
        (cons val (inner port)))))
  (let* ((file (open-input-file filename)))
    (inner file)))
